// <auto-generated />
using HRMNS.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMNS.Data.EF.Migrations.SqliteMigrations
{
    [DbContext(typeof(PayrollDBContext))]
    [Migration("20230517040031_initPayrollDB")]
    partial class initPayrollDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("HRMNS.Data.Entities.Payroll.BANGLUONGCHITIET_HISTORY_PR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AbilityAllowance")
                        .HasColumnType("REAL");

                    b.Property<double>("BasicSalary")
                        .HasColumnType("REAL");

                    b.Property<string>("BoPhan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DanhGia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("DieuChinhCong_Total")
                        .HasColumnType("REAL");

                    b.Property<string>("DoiTuongPhuCapDocHai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoiTuongThamGiaCD")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoiTuongTruyThuBHYT")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("GioLamThemTrongCT_150")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongCT_200")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongCT_210")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongCT_270")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongCT_300")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongCT_390")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_150")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_200")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_210")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_270")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_300")
                        .HasColumnType("REAL");

                    b.Property<double>("GioLamThemTrongTV_390")
                        .HasColumnType("REAL");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("HarmfulAllowance")
                        .HasColumnType("REAL");

                    b.Property<string>("HieuLucCapBac")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("HoTroAT_SinhVien")
                        .HasColumnType("REAL");

                    b.Property<decimal>("HoTroCongDoan")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoTroNgayThanhLapCty_CaDemCT_TruocLe")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroNgayThanhLapCty_CaDemTV_TruocLe")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroNgayThanhLapCty_CaNgayCT")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroNgayThanhLapCty_CaNgayTV")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroPCCC_CoSo")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_150")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_200_CN")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_200_NT")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_270")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_300")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecCT_390")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_150")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_200_CN")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_200_NT")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_270")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_300")
                        .HasColumnType("REAL");

                    b.Property<double>("HoTroThoiGianLamViecTV_390")
                        .HasColumnType("REAL");

                    b.Property<decimal>("InsentiveStandard")
                        .HasColumnType("TEXT");

                    b.Property<double>("LivingAllowance")
                        .HasColumnType("REAL");

                    b.Property<string>("MaBoPhan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNV")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("NgayCongChinhThucBanDem")
                        .HasColumnType("REAL");

                    b.Property<double>("NgayCongChinhThucBanNgay")
                        .HasColumnType("REAL");

                    b.Property<double>("NgayCongThuViecBanDem")
                        .HasColumnType("REAL");

                    b.Property<double>("NgayCongThuViecBanNgay")
                        .HasColumnType("REAL");

                    b.Property<string>("NgayNghiViec")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NgayVao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("NghiKhamThai")
                        .HasColumnType("REAL");

                    b.Property<double>("NghiKhongLuong")
                        .HasColumnType("REAL");

                    b.Property<double>("NghiViecCoLuong")
                        .HasColumnType("REAL");

                    b.Property<double>("NghiViecKhongThongBao")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Official_Late_Come_Early_Leave_Time")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionAllowance")
                        .HasColumnType("REAL");

                    b.Property<double>("Probation_Late_Come_Early_Leave_Time")
                        .HasColumnType("REAL");

                    b.Property<double>("SeniorityAllowance")
                        .HasColumnType("REAL");

                    b.Property<int>("SoConNho")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoNgayLamCaDemTruocLe_CT")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayLamCaDemTruocLe_TV")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayLamCaDem_CT")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayLamCaDem_TV")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayNghi70")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayNghiBu_AL30")
                        .HasColumnType("REAL");

                    b.Property<double>("SoNgayNghiBu_NB")
                        .HasColumnType("REAL");

                    b.Property<decimal>("SoNguoiPhuThuoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTK")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("TT_Tien_GioiThieu")
                        .HasColumnType("REAL");

                    b.Property<double>("TV_NghiKhongLuong")
                        .HasColumnType("REAL");

                    b.Property<string>("TenNV")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThangNam")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThuocDoiTuong_BHXH")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Thuong")
                        .HasColumnType("REAL");

                    b.Property<double>("TongNgayCongThucTe")
                        .HasColumnType("REAL");

                    b.Property<double>("TraTienPhepNam_Total")
                        .HasColumnType("REAL");

                    b.Property<double>("TruQuyPhongChongThienTai")
                        .HasColumnType("REAL");

                    b.Property<string>("UserCreated")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModified")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BANGLUONGCHITIET_HISTORY_PR");
                });

            modelBuilder.Entity("HRMNS.Data.Entities.Payroll.HR_SALARY_PR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AbilityAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoiTuongPhuCapDocHai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoiTuongTruyThuBHYT")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FullAttendanceSupport")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HarmfulAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoTroATVS_SinhVien")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoTroCongDoan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncentiveLanguage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncentiveOther")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncentiveSixMonth1")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncentiveSixMonth2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncentiveStandard")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncentiveTechnical")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LivingAllowance")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNV")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PCCC_CoSo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionAllowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeniorityAllowance")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoConNho")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoNguoiPhuThuoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThamGiaCongDoan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThuocDoiTuongBaoHiemXH")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCreated")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModified")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HR_SALARY_PR");
                });
#pragma warning restore 612, 618
        }
    }
}
